### ISSUE TITLE
24 hour plot y axis scaling issue

### ISSUE THREAD

**Issue by tshyka** [gulfofmaine/Neracoos-1-Buoy-App#1098]
There is a y axis scaling issue with a wind data plot where some of the data is off the plot. See image below,
![Screen Shot 2021-03-04 at 10 48 16 AM](https://user-images.githubusercontent.com/22799875/109990585-89fffd00-7cd7-11eb-8841-499b1ba29980.png)
![Screen Shot 2021-03-04 at 10 48 39 AM](https://user-images.githubusercontent.com/22799875/109990644-96845580-7cd7-11eb-9a91-169f5d22b933.png)

**Comment by abkfenris** [comment]
I haven't been able to reproduce this issue on either very wide or narrow monitors.
