### ISSUE TITLE
Add icons to show plots can expand and to indicate outbound links

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1112]
- Add an expand icon to the Latest Condition plots to indicate that they can be enlarged
[https://fontawesome.com/icons/expand-alt?style=solid](https://fontawesome.com/icons/expand-alt?style=solid)

- Add an outbound link icon to More Info links
[https://fontawesome.com/icons/external-link-alt?style=solid](https://fontawesome.com/icons/external-link-alt?style=solid)

**Comment by abkfenris** [comment]
Should the table also get expand icons since they are sneaky links too?
<img width="229" alt="image" src="https://user-images.githubusercontent.com/1296209/110382553-13d9fe00-8029-11eb-93ea-a46f45a40bbf.png">

**Comment by youngmorse** [comment]
I don't think so. Underlines make it pretty clear they are links. Too many of those outbound links would look busy I think.

**Comment by abkfenris** [comment]
Released with [v0.6.7](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.6.7)
