### ISSUE TITLE
Change chart line style for observations on forecast plots

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1113]
On the forecast plots where observations are also available, investigate changing the line type to a dashed line (short or long) to differentiate from the forecast. Related to issue about setting specific colors for plot lines.

**Comment by abkfenris** [comment]
This will take some restructuring of how we pass data to charts, so it probably best to combine with #1114

**Comment by abkfenris** [comment]
Would it make more sense for the forecasts to have the dashed lines, rather than the observations? 

Dashed makes it seem more unknown than a solid observation to me.

**Comment by abkfenris** [comment]
Solid observation and dashed forecasts: 

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1296209/115064682-34fcfc80-9ebb-11eb-9208-dbaf1193279b.png">

**Comment by abkfenris** [comment]
Coloring the tooltips 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1296209/115067738-5364f700-9ebf-11eb-8559-81eaca59ffbd.png">

**Comment by abkfenris** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1296209/115073300-20723180-9ec6-11eb-81e0-c7c2c2e6f122.png">


@m-wessler has told me I'm wrong

**Comment by youngmorse** [comment]
Dashed is how our friends at [SECOORA](https://mwp.secoora.org/?health=Off&quality=Off&units=English&duration=3%20days&maps=nws_wwa,storm_tracks&legend=Off&forecast=Point&hti=&nhc=undefined&nhcWinds=undefined&sst=&current=&datum=MLLW&windPrediction=wind%20speed%20prediction&region=MWP&bbox=-81.877,24.456,-81.877,24.456&iframe=null&mode=home&platform=SANF1) are doing it so there would be some consistency to doing it that way. It looks a little odd with two dashed lines where there are multiple forecasts on one plot, but I think the first example looks good!
