### ISSUE TITLE
Set color for lines in charts

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1114]
The colors are arbitrarily changing on some of the plots. It's most noticeable on the forecast/observation plots and will sometimes change the series color from green to orange while it's reloading. Investigate how we can set the colors so they are fixed by data type and consistent between plots.

**Comment by abkfenris** [comment]
This will take some deeper digging into how Highcharts assigns colors. 

We may want to look at creating a library/cycle of colors that we feed to the charts and be more explicit about what ends up what color. Which is probably best implemented with #1113

**Comment by abkfenris** [comment]
Ok, I've got it so we can pass specific colors to be displayed to the plot, and it will override the default cycle. 

Right now I've got it using NERACOOS blue for the observation, and [a ColorBrewer scheme](https://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=3) for the forecasts.

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/1296209/115064442-ebacad00-9eba-11eb-8439-77246628fee7.png">

Let me know if there is a better set of colors to be using.

**Comment by abkfenris** [comment]
Coloring the tooltips to match the line colors:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/1296209/115067801-67105d80-9ebf-11eb-9245-0656ba32ea49.png">

**Comment by abkfenris** [comment]
Using colors from the NERACOOS visual guide (and fixed styling elsewhere to match).

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/1296209/115080741-42bd7c80-9ed1-11eb-8042-7e09ca3ab038.png">

**Comment by youngmorse** [comment]
This is looking great @abkfenris! It would be good to try and incorporate the NERACOOS color scheme if we can. I'm attaching the neracoos palatte Julianna created as a PDF and I used [coolors.co](https://coolors.co/083d52-178596-2ab78f-ffcd22-ffae6d) to put the palatte online. Maybe use the 'NERACOOS blue' for the obs (which you may be using already), the 'Coastal Meadow' or 'Metallic Seaweed' for the green and see if the rich yellow works in place of the orange you are using? I think the lighter orange in the palatte might be too light, but if Buoy Yellow doesn't work, I think the orange you've got would be ok.
[neracoos palette.pdf](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/files/6327814/neracoos.palette.pdf)
