### ISSUE TITLE
Disable links to ERDDAP underneath plot

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1115]
For now, disable and hide the links to the specific dataset on ERDDAP that appear under the observation and forecast charts. We will figure out how best to add the ability to access the underlying data when we work on the evolution of Graphing and Download. We can also add links to ERDDAP on the about page for each of the data providers.

**Comment by abkfenris** [comment]
Released with [v0.6.7](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.6.7)
