### ISSUE TITLE
Data source links under forecast plots

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1116]
Similar to the ERDDAP link request, disable the links to the datasets. Instead, add this statement and link to about page.
"For more information on the models and data used in this plot, visit the **about page.**"

**Comment by abkfenris** [comment]
Released with [v0.6.7](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.6.7)
