### ISSUE TITLE
Clarify forecast plot labels to show observations vs forecast

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1117]
It's not abundantly clear that one of the lines on these charts is an actual observation. Append - obs or - forecast to the dataset label name on the forecast plots.

**Comment by abkfenris** [comment]
Released with [v0.6.7](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.6.7)
