### ISSUE TITLE
Issue with values in All observations table where variable has multiple depths

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1362]
Noticed a strange behavior with the UMaine buoys where variables with multiple depths are repeating the same value under the  'All observations'.

[https://mariners.neracoos.org/platform/M01%20-%2044037/observations/all](https://mariners.neracoos.org/platform/M01%20-%2044037/observations/all)

Seems to be an issue for conductivity, salinity, Sigma T, and water temperature. The plots are displaying the data for each depth correctly and the value in the All observations list seems to  be the surface reading. Picture of M01 below:

<img width="473" alt="Screen Shot 2021-07-13 at 3 00 40 PM" src="https://user-images.githubusercontent.com/3279645/125510347-958d74cf-fe8c-46f0-af1f-2248d88ada64.png">

**Comment by abkfenris** [comment]
Released in [v0.7.1](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.7.1) on 7/14/2021.
