### ISSUE TITLE
Layout of map/table has changed

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#1590]
A couple of layout issues after last update. The map and data table have switched positions and the menu items are now flush left instead of right. 

Per Alex, probable issue with latest (major) Bootstrap update and changes to styling rules.

![Screen Shot 2021-11-11 at 9 45 26 AM](https://user-images.githubusercontent.com/3279645/141320876-04a4c002-beaa-4b3b-b726-4c1a4737183f.png)

**Comment by abkfenris** [comment]
Fixed and deployed as [0.10.2](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.10.2)
