### ISSUE TITLE
Initial navigation to region doesn't trigger zoom

### ISSUE THREAD

**Issue by abkfenris** [gulfofmaine/Neracoos-1-Buoy-App#2653]
When a user first selects a region from the drop down menu, the map doesn't zoom to the region. Subsequent region choices do cause the region to update, whether that's from a region or a platform page.

https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/1296209/8faf137b-9079-4d48-8cc8-3dc09082dfce

**Comment by abkfenris** [comment]
And I biffed that as I was testing on prod, not dev. The not zooming on initial region selection is an existing issue on prod. It looks like on dev it usually isn't zooming to the regions at all. I'm not sure the rhyme or reason when it does decide to zoom.


https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/1296209/81c8fe19-9b84-473d-a1c0-ae74d1a15695

**Comment by Adelle-Pitsas** [comment]
Looks like the issue is stemming from the `useEffect` in `map/index` not being triggered by a change in region. Added `view` and `platform` to catch any change in region to therefore update the zoom.
