### ISSUE TITLE
NDBC wave data not getting to Sea Eagle ERDDAP 

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#2686]
More NDBC data weirdness. I think I found the problem while I was writing up the issue, so there is a lot of detail!

Something odd is going on with the wave data (WVHT, APD, DPD) for the NDBC buoys that we are ingesting into Sea Eagle ERDDAP. I noticed the wave data readings are on NDBC but are not getting updated in ERDDAP. Digging in a little deeper, I noticed there are occasional wave readings for two of the buoys ([44011](https://data.neracoos.org/erddap/tabledap/NDBC_44011.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-20T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z), [44025](https://data.neracoos.org/erddap/tabledap/NDBC_44025.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-20T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)) but generally only once per day. And [44090](https://data.neracoos.org/erddap/tabledap/NDBC_44090.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-20T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) is out there serving up wave data at every reading.

I looked at the two stations that have sparse data and it seems to be a conflict with the timing of when we are grabbing the hourly reading. The pattern with 44025 is that at 22:30, the reading is fine, then the next reading is 23:10 and has wave data. The next reading is 00:30, then continues on that pattern with no wave data until 22:30 swings around again. 44011 had a similar pattern, but the hourly ERDDAP time stamp jumps between the :30 and :40 over the day. 

<img width="1214" alt="Screen Shot 2023-11-22 at 2 07 38 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/9fb300f6-c3ff-4af2-878c-62f2353d178a">

Looking at the individual NDBC text files for the buoys, the frequency of readings for most of these buoys is every 10 minutes. (44090 is every 30 minutes). The wave data is more inconsistent and is only coming in on some of those readings. There does seem to be a pattern on buoys reporting every 10 minutes. The wave data comes in on the :10, :20:, :50, and sometimes :40 but does not seem to ever be on the :00 or :30 minute readings. 

44090 is consistently getting wave data into ERDDAP but only has NDBC readings on the :00 and the :30 and that lines up with the timing of the hourly reading time stamp on ERDDAP (on the :30).

<img width="1231" alt="Screen Shot 2023-11-22 at 2 12 23 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/10503c69-0c35-48af-aab7-889db06a267c">

The wave data does appear on the [Latest Obs text file](https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt) but because it's intermittent and we appear to generally be checking on the :30 or :40, we usually miss it for the ten minute buoys. 

If I remember right, we were staying with the hourly processing interval because the workflow was taking a while to run in Dagster. If we move this process up to run every 30 minutes but staggered - the :10 and the :40 or the :20 and the :50 it seems like we should catch these readings? 

Links to the ERDDAP data, the NDBC text file, and NDBC station page for the buoys we are ingesting into ERDDAP that have wave data:

 44005 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44005.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44005.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44005)
44007 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44007.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44007.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44007)
44008- [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44008.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44008.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44008)
44011 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44011.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44011.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44011)
44013 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44013.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44013.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44013)
44018 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44018.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44018.txt) | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44018)
44020 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44020.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44020.txt)  | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44020)
44025 - [ERDDAP ](https://data.neracoos.org/erddap/tabledap/NDBC_44025.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44025.txt)  | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44025)
44027 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44027.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44027.txt)  | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44027)
44065 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44065.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44065.txt)  | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44065)
44090 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44090.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)  | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44090.txt)  | [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44090)

**Comment by Dylan-Pugh** [comment]
Changes here should help address this:

https://github.com/gulfofmaine/NERACOOS_ERDDAP_K8S/pull/240
https://github.com/gulfofmaine/NERACOOS_ERDDAP_K8S/pull/474

**Comment by Dylan-Pugh** [comment]
Tracking here - using this [ERDDAP query to see if there's actual data](https://data.neracoos.org/erddap/tabledap/NDBC_44011.htmlTable?platform_id%2Ctime%2CWVHT%2CDPD%2CAPD&time%3E=2023-12-01T00%3A00%3A00Z&WVHT%3E=0):

- [ ] 44005 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44005.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44005.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44005)
- [ ] 44007 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44007.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44007.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44007)
- [ ] 44008- [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44008.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44008.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44008)
- [ ] 44011 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44011.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44011.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44011)
- [ ] 44013 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44013.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44013.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44013)
- [ ] 44018 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44018.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44018.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44018)
- [ ] 44020 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44020.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44020.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44020)
- [ ] 44025 - [ERDDAP ](https://data.neracoos.org/erddap/tabledap/NDBC_44025.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z)| [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44025.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44025)
- [ ] 44027 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44027.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44027.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44027)
- [ ] 44065 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44065.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44065.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44065)
- [ ] 44090 - [ERDDAP](https://data.neracoos.org/erddap/tabledap/NDBC_44090.htmlTable?platform_id%2Ctime%2Clatitude%2Clongitude%2CWDIR%2CWSPD%2CGST%2CWVHT%2CDPD%2CAPD%2CMWD%2CPRES%2CPTDY%2CATMP%2CWTMP%2CDEWP%2CVIS%2CTIDE&time%3E=2023-11-21T00%3A00%3A00Z&time%3C=2023-11-22T16%3A40%3A00Z) | [NDBC text ](https://www.ndbc.noaa.gov/data/realtime2/44090.txt)| [NDBC station page](https://www.ndbc.noaa.gov/station_page.php?station=44090)

**Comment by Dylan-Pugh** [comment]
This is looking good to me- reading are still intermittent, but ERDDAP is now lining up with what I'm observing on NDBC. I'll close for now, @youngmorse, feel free to reopen if you see anything amiss!
