### ISSUE TITLE
Some routes not working on refresh or direct navigation

### ISSUE THREAD

**Issue by Adelle-Pitsas** [gulfofmaine/Neracoos-1-Buoy-App#2691]
I've noticed some platform routes don't work on refresh or on direct navigation -- would be an issue if someone was trying to access a specific url (say [https://mariners-dev.aws.neracoos.org/platform/GREAT_BAY/observations/sea_water_salinity](https://mariners-dev.aws.neracoos.org/platform/GREAT_BAY/observations/sea_water_salinity) and it led them to our error page.)

Some routes I've noticed it on: 
- Any observation routes [https://mariners-dev.aws.neracoos.org/platform/BHBM3/observations/air_pressure_at_sea_level](http://localhost:3000/platform/BHBM3/observations/air_pressure_at_sea_level)
- Any forecast routes [https://mariners-dev.aws.neracoos.org/platform/BHBM3/forecast/air_temperature](http://localhost:3000/platform/BHBM3/forecast/air_temperature)

**Comment by abkfenris** [comment]
Good catch. Now I remember encountering that while getting the initial routing working, but I guess I forgot to continue testing for it. 

Probably would be a good set of Playwright tests.

**Comment by abkfenris** [comment]
Do you mean going to say https://mariners-dev.aws.neracoos.org/platform/E01 on a fresh load or reload? While it would be nice to have a more focused zoom on the platform in that case, we're not doing that currently so it shouldn't be a blocker (at least compared to inaccessible routes above). 

Or do you mean keeping the zoom from pre-reload? I wouldn't worry about persisting zoom state across full reloads.

**Comment by Adelle-Pitsas** [comment]
Its the latter--Sounds good. I worry about saving zoom state when fully reloading

**Comment by Adelle-Pitsas** [comment]
Update: So this is a hydration error where a full refresh would attempt to rerender some components on the page, but they didn't match what was rendered on the server thus throwing this error: 
`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`
Taking out the `DehydratedPlatforms` wrapper in `/app/(platformMap)/@sidebar/platform/[platformId]/page.tsx` removes the error and allows the page to render--but this solution only works with `yarn dev` so still working on a solution that works with a build step.

**Comment by Adelle-Pitsas** [comment]
Okay got it to work but it feels a bit shoddy--After removing the DehydratedPlatforms wrapper, I also did a check to see if the component was already mounted on the client so it wouldn't try to rerender and not match. Going to throw up a draft PR with the changes and would love to chat about what the `DehydrationPlatforms` wrapper was doing or if it was leftover from pre-Next.js an what the consequences might be of ripping it out.

**Comment by Adelle-Pitsas** [comment]
> Aren't we using `DehydratedPlatforms` further up the tree (`/app/(platformMap)/layout.tsx`-ish)? Shouldn't that mean that we don't need it again deeper down?

The highest place to the root layout we are using it is `/app/(platformMap)/@sidebar/platform/[platformId]/page.tsx` but its not in `/app/(platformMap)/layout.tsx`

**Comment by Adelle-Pitsas** [comment]
Throwing these here as I thought they were helpful in troubleshooting: 
https://blog.logrocket.com/react-hydration-pre-rendered-html/
Very simple example: https://blog.jannikwempe.com/react-pre-rendering-and-potential-hydration-issue#heading-the-cause-of-my-problem
