### ISSUE TITLE
Adding a cannonical link

### ISSUE THREAD

**Issue by abkfenris** [gulfofmaine/Neracoos-1-Buoy-App#2733]
This is from a conversation with a frequent user and relates to some of the NDBC data issues that Dylan has been fighting.

This user usually checks https://mariners.neracoos.org/platform/44007 to look at the waves for surfing. If we don't have recent data, he'll click through to NDBC, but wondered if it would be possible to link directly to the buoy page, rather than the root of the NDBC. 

<img width="669" alt="image" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/1296209/a8c9c35b-60a0-47ef-84c9-0c8767914886">

https://github.com/gulfofmaine/Neracoos-1-Buoy-App/blob/81428409125eedcbf419b152cb8508a805456fc0/src/Features/ERDDAP/Platform/Info/index.tsx#L34-L38

I'm guessing we'll probably want to leave the StationInfo program attribution as is, but we could either add an optional additional link, or maybe have a link under the More Info menu. Either way could be an easy tweak in Buoy Barn to add to the API.

<img width="505" alt="image" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/1296209/bcc14edd-ec1b-4b1e-81e5-14510d05d881">

@youngmorse @Adelle-Pitsas any thoughts?

**Comment by abkfenris** [comment]
Thinking a little further while copying screenshots, what about having any number of More Info links related to a platform? Each could have it's own URL and title defined in Buoy Barn which would give us some flexibility to link to say UMaine status and data pages.

**Comment by Adelle-Pitsas** [comment]
Definitely seems doable and I would imagine it would be pretty simple to put the link in the more info menu.

**Comment by Adelle-Pitsas** [comment]
> Thinking a little further while copying screenshots, what about having any number of More Info links related to a platform? Each could have it's own URL and title defined in Buoy Barn which would give us some flexibility to link to say UMaine status and data pages.

Thinking of any design changes with this? With additional links, might be helpful to have them more easily accessible than opening another menu. Lots of times additional links are put into a card on the side/bottom. Like this example from employee nav: 
<img width="1721" alt="Screenshot 2024-01-10 at 2 40 03 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/108096652/7d1e09bb-d1cd-40e2-a456-01b56127ce3d">

**Comment by abkfenris** [comment]
I think adding a new card for all platform views might mess with the current visual hierarchy, but maybe there is a place for one on the Latest Conditions view. 

What if we start with being able to add a dynamic number of links to 'More info', and then we can later explore if we want to have a way to add cards to Latest Conditions (maybe an option when creating an alert to have it show in Latest conditions, rather than above the Station Info)?

**Comment by Adelle-Pitsas** [comment]
Yep, sounds like a good plan

**Comment by youngmorse** [comment]
I think this is a good idea. I don't think we want to drive folks off the website right away so linking to NDBC station page right after the attribution might be counter productive. 

I think I like the approach of starting with adding dynamic # of links under 'More Info'. 

The old buoy map used to show links under the latest data table for the other data products for that station like: All Data From Station, Recent History, Forecast, Graphing & Download, as well as some text based station detail pages that we don't have in MD. And 'More Data' links went to Marine Forecast and Tides. These links and data are all accessible in the tabs more or less but may not be as intuitive as when they are printed out in a list like Adelle is suggesting. 

So adding dynamic links in BB that show up in 'More Info' tab for now, and maybe a future iteration would be to make these 'More Info' links always visible below the latest conditions plots or something along those lines.

![neracoos_buoy copy](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/a8c00503-cffb-4be1-8952-e2ba71809632)

**Comment by tshyka** [comment]
The use case that Alex described - looking for wave data from 44007 on MD and then going to NDBC if there is no recent data is exactly what I do. I have also talked to mariners who go to NDBC because they provide a detailed wave summary (see screenshot below). Mariners have requested that we include this detailed wave data for the NDBC buoys on MD and is something we should consider for future enhancements. Anyway, I like the solution that you've outlined to make it easier for users to get to the NDBC page for a specific buoy you could do the same for the CDIP buoys on MD. CDIP has an individual station page for each station (e.g. https://cdip.ucsd.edu/m/products/?stn=260p1)
Detailed wave summary:
![Screen Shot 2024-01-10 at 3 39 28 PM](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/22799875/8eb92922-9c86-489b-be09-21eff996db2f)

**Comment by abkfenris** [comment]
Implementation on the Buoy Barn side is https://github.com/gulfofmaine/buoy_barn/pull/997
