### ISSUE TITLE
Units should stay the same when changing stations

### ISSUE THREAD

**Issue by Adelle-Pitsas** [gulfofmaine/Neracoos-1-Buoy-App#2858]
- [ ] Unit system selection reverts back to English from Metric when you change stations or change time range. Works okay with Datum selection change (hard to show in a screen shot but easy to replicate!)
<img width="546" alt="Screenshot 2024-04-12 at 4 20 53 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/3e930fa4-e4da-46ac-87fd-1e7bd3fb7ef0">
<img width="469" alt="Screenshot 2024-04-12 at 4 21 02 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/bf91b59c-fe44-4e11-b4cb-19b124686f9e">

_Originally posted by @youngmorse in https://github.com/gulfofmaine/Neracoos-1-Buoy-App/issues/2701#issuecomment-2052472850_

**Comment by abkfenris** [comment]
We might want to think about using URL params and/or cookies for current unit and datum selections and to persist defaults for users.

**Comment by Adelle-Pitsas** [comment]
Updating here as I've been working on the unit selections and default state on WL pages. PR #2899 puts unit selection in session storage to persist over url changes and refreshes. It will revert to default if a user opens a new tab (a new session).

Datum selection is currently included in url params and persists on sensor/url change and refreshes. It defaults to MLLW when a user first selects a sensor from the base `/water-level` url
