### ISSUE TITLE
Tide gauge data not available in Water Level Dashboard

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#3237]
The data links seem to be broken in both [Dev](https://mariners-dev.aws.neracoos.org/water-level/sensor/CASM1) and [Prod MD](https://mariners.neracoos.org/water-level/sensor/CASM1) for the water level dashboard. I didn't test them all but it seems broken for NOAA, Hohonu, and NERACOOS gauges that I checked. Data in ERDDAP looks good. Realize this may be in flux with the recent updates you are working on with BB and flood thresholds, but wanted to add the issue in case it's not!

![Screenshot 2024-11-22 at 8 56 41 AM](https://github.com/user-attachments/assets/f479512f-2a5c-4d30-8fc4-75409e53f612)

**Comment by abkfenris** [comment]
I've had to disable the updating of timeseries from https://coastwatch.pfeg.noaa.gov/erddap/tabledap/nosCoopsWLTPHL.html as we're not set up to truly handle datasets that are just high/low predictions yet, even if we now have enough ways to configure things in Buoy Barn to handle them.

**Comment by abkfenris** [comment]
It looks like the big issue (which also was causing a lot of other platforms to be out of date) was that the hourly periodic dataset refresh wasn't happening. It appears the container was running out of memory, but not throwing any alerts, just silently (well complaining about Numpy depredations...) failing before figuring out if the database was accessible.

**Comment by youngmorse** [comment]
Thanks @abkfenris! BTW, I set up that coastwatch dataset nosCoopsWLTPHL.html High/Low timeseries thinking Adelle and I might be able to test some front end changes but we realized we were stuck because it was only in MLLW. It wasn't actually being used by any of the stations.
