### ISSUE TITLE
Add additional units to current conditions data table 

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#49]
From Tom - "Display the latest observation data with units like it is being done on the current buoy map e.g. wind direction is displayed as compass points with degrees in parentheses and temp is F with C in parentheses."

You are already doing this in the small charts, so just adding the additional units to the data table should make him happy.  Screenshot from current buoy map for reference.

![screen shot 2018-11-15 at 10 09 15 am](https://user-images.githubusercontent.com/3279645/48561822-d16fde80-e8be-11e8-9af4-94242422a567.png)

**Comment by abkfenris** [comment]
This was taken care of with the unit toggling in #299 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/1296209/106806992-9d676c00-6636-11eb-9454-17f87b03a69b.png">
