### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#88]
There are several open issues with units #70 #44 #49 
We need to decide on a common solution to all of them. We recommend default of using native data unit (conversion, conversion) everywhere there is a value (tool tip on graph, latest data).  The larger request is a feature where users can select Metric or Imperial units and all data will update. Will update this issue once we resolve plan forward.

**Comment by abkfenris** [comment]
Closed with #299
