### ISSUE TITLE
Toggle units

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#89]
Initial issue request for creating functionality to toggle between metric and imperial units. Ideal implementation is that user selects preference and all data are shown in preferred format. Will require setting cookie with preference and organizing data types into categories. 

(From Tom list) Resolve ability to choose english/metric units with toggle like SECOORA or by precalculating values.

**Comment by abkfenris** [comment]
Closed with #299
