### ISSUE TITLE
Preferred Units

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/Neracoos-1-Buoy-App#99]
This will serve as the official source for parameter and preferred unit. 

| Parameter            	| Preferred Unit 	| Alternative Units 	| Alt Units 	|
|----------------------	|----------------	|-------------------	|-----------	|
| Temp (air and water) 	| F              	| C                 	|           	|
| Wave Height          	| ft             	| m                 	|           	|
| Wind Speed           	| knots          	| m/s               	| knots     	|
| Visibility           	| miles          	| meters            	|           	|
| Dominant wave period          	| seconds         	|             	|           	|
| Direction (wind, wave, current)          	| degrees          	| compass directions NNW           	|           	|
|         	|         	|         	|           	|
|         	|         	|         	|           	|
|         	|         	|         	|           	|

**Comment by abkfenris** [comment]
Closed with #299
